# Generated by Django 3.2.18 on 2024-03-31 14:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='team_members',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
