# Generated by Django 3.2.18 on 2024-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0002_registration_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='team_members',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
